apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-aws-cvs-vp-secret
type: Opaque
stringData:
  apiKey: znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE
  secretKey: rR0rUmWXfNioN1KhtHisiSAnoTherboGuskey6pU
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-aws-cvs-vp
spec:
  version: 1
  storageDriverName: aws-cvs
  backendName: tbc-aws-cvs-vp
  apiURL: https://cds-aws-bundles.netapp.com:8080/v1
  apiRegion: us-east-1
  credentials:
    name: backend-tbc-aws-cvs-vp-secret
  nfsMountOptions: nfsvers=3,proto=tcp,timeo=600
  defaults:
    snapshotReserve: '10'
    exportRule: 10.0.0.0/24
    size: 1000Gi
  labels:
    cloud: aws
  storage:
    - labels:
        performance: extreme
      serviceLevel: extreme
      defaults:
        snapshotReserve: '5'
        exportRule: 0.0.0.0/0
    - labels:
        performance: premium
      serviceLevel: premium
    - labels:
        performance: standard
      serviceLevel: standard
  deletionPolicy: retain
