apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: san-snap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: san-basic
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: san-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io