apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-nfs-pvc
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: manual-nfs-pv
  resources:
    request:
      storage: 1Gi