apiVersion: v1
kind: Pod
metadata:
  name: web1
spec: 
  containers:
  - name: web1
    image: httpd:2.2
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: local-store
  volumes:
  - name: local-store
    hostPath:
      path: /local_volumes
      type: Directory